### ISSUE TITLE
mpyc.cmd_put() broken?

### ISSUE THREAD

**Issue by jedie** [kr-g/mpycntrl#1]
I tried your project to sync local source to the device, but mpyc.cmd_put() seems to be broken?
The error is reproducible in the second block:
```
(debug) sending 0 0 256 b'3c6874...072'
(debug) received [b'raw REPL; CTRL-B to exit\r\n', b'>']
(debug) received []
(debug) sending 1 256 256 b'656c3...765'
(debug) received []
Traceback (most recent call last):
  File "/home/jens/repos/micropython-sonoff-webswitch/upload_files.py", line 21, in <module>
    verbose=True,
  File "/home/jens/repos/micropython-sonoff-webswitch/utils/sync.py", line 148, in sync
    SyncToDevice(src_path, verbose=verbose).update_device()
  File "/home/jens/repos/micropython-sonoff-webswitch/utils/sync.py", line 107, in update_device
    mpyc.cmd_put(fnam=item.name, content=f.read())
  File "/home/jens/.local/share/virtualenvs/micropython-sonoff-webswitch-q5T6TSa7/lib/python3.6/site-packages/mpycntrl/mpycntrl.py", line 347, in cmd_put
    r = self.sendcmd( cmd % (dest, pos / 2, part ) )
  File "/home/jens/.local/share/virtualenvs/micropython-sonoff-webswitch-q5T6TSa7/lib/python3.6/site-packages/mpycntrl/mpycntrl.py", line 128, in sendcmd
    raise Exception("could not enter raw-repl")
Exception: could not enter raw-repl
```

**Comment by kr-g** [comment]
Hi Jens,
Have you tried to increase the timeout?
The Default of 0.35 given by me in the example is probably too short.
Cheers Karl


Jens Diemer <notifications@github.com> schrieb am Fr., 6. Dez. 2019, 21:10:

**Comment by jedie** [comment]
I will test it, thanks.

**Comment by jedie** [comment]
I set timeout to 1sec with https://github.com/jedie/micropython-sonoff-webswitch/commit/5fb0c37c30a8c4eb6d6a040cd2cae2b25574eec9

This fixed the issues... But it seems that this is not a "timeout" it's more a "Wait 1 sec.", isn't it? SO every send a block takes 1 sec. That's boring.

**Comment by kr-g** [comment]
The timeout is for pyserial what is used for accessing the serial device.
You can try probably something inbetween 0.35 and 1.
I will add a stress test to the Sample Code too

Jens Diemer <notifications@github.com> schrieb am Sa., 7. Dez. 2019, 10:22:

**Comment by kr-g** [comment]
Your Report #1 and #2 are related so please let me know if it works without the 2nd process (thonny) and the 0.35 timeout

**Comment by jedie** [comment]
No #2 is not related...
I currently use 1 sec. via `with mpyc.timeout(timeout=1):`

**Comment by kr-g** [comment]
As i understood now is that the orginal cause #1 was not the timeout, it was that two processes #2 access the serial Interface at the same time. So #2 is resolved because its not a bug.
#1 is also not a bug because its related to timing what is very specific to the users setup. It might be interessting for other developers too if you could share your experience. Thats all.

**Comment by kr-g** [comment]
not a bug, resolved by different timeout parameter
check also the latest version together with pttydev (experimental) to gain better serial performance

**Comment by jedie** [comment]
I use it with https://github.com/jedie/micropython-sonoff-webswitch/commit/e48c115ffa08ecba3b3a3308ce7d8e8529e0aee7 and yes, it's faster...


But it seems that my WiFi OTA is still faster. Shouldn't be, right?

**Comment by kr-g** [comment]
hallo jens,

da das hier wohl nirgends im web auftaucht... einfach in deutsch.

das mit dem ota geht über wifi zunächst einmal schneller als seriell.
liegt einfach in der natur der sache...

dein ota update ist ganz interessant gemacht. verfolgt aber einen anderen
ansatz soweit ich das gesehen habe.

bei dem ganzen ota hab ich _generell_ bauchschmerzen dass da ein stück
software auf dem microcontroller laufen muss.
(ausser man baut das als code freeze in die firmware ein...)

deswegen auch die idee mit der "fernsteuerung" und webrepl.
da ist es egal ob beim update was schief geht und der microcontroller
"einsam" im repl rumhängt,
weil der ota software anteil dann ggf nicht mehr in die höhe kommt.
den genauen ablauf kann man dann auch besser kontrollieren.
naja. ist einfach ein anderer ansatz als zb git repo aus dem netz zu holen
und aufzuspielen.
diesen ansatz gibt es ja auch.
ich bin aber mehr so der "knöpfchen-drücker-typ-und-jetzt-passiert-was-typ"
;-)

na egal. (soviel zur theorie...)

bei meinem ansatz wird leider, im gegensatz zu deinem ansatz, die
datenmenger auch noch verdoppelt da alles als hex-string rübergeschiben
wird.
das macht es natürlich noch langsamer. aber mir ist da auch noch keine
bessere alternative eingefallen.
ausser vielleicht ein code-fragment "temporär" rüberscheiben und das macht
dann einen socket/pipe/stream/was-weiss-ich auf übder den dann die
binärdaten übertragen werden.
aber da kann auch wieder viel bei schiefgehen.
aber das ist so eine optimierung die ich nicht so gut finde weil der
aktuelle ansatz einfach komplett einfach und stabil ist.
vielleicht klappt das mit dem pttydev und websockets demnächst dann merkt
man das wahrscheinlich nicht mehr so.
da hatte ich aber noch keine zeit im detail nachzuforschen... das problem
ist aber wohl im websocket_client und nicht auf meiner seite... aber egal
... wird sich ggf zeigen wo es hakt.

übrigens kann du bei cmd_put noch etwas "drehen"

default hatte ich so gesetzt damit es auch auf kleinen geräten läuft
blk_size=256

beim esp8266 solte aber auch einiges mehr gehen (das hängt davon ab wie
zerstückelt dein ram ist...also speicherverwaltung)
probier mal
blk_size=2048

ging bei mir bislang immer, darüber wird es eng... also 4096 ging nicht
mehr.
du kannst natürlich auch eine andere grösse wählen, dass ist nicht an 2er
potenzen gebunden.

das sollte auch noch mal was bringen von der geschwindigkeit.
muss ich mal generell in der doku nacharbeiten :-/


schönes wochenende!

gruss karl







Am Fr., 13. Dez. 2019 um 16:58 Uhr schrieb Jens Diemer <
notifications@github.com>:
