### ISSUE TITLE
could not enter raw-repl if e.g.: thonny is connected...

### ISSUE THREAD

**Issue by jedie** [kr-g/mpycntrl#2]
If thonny is already connected to the device, "could not enter raw-repl" always comes.

I just need to disconnect thonny, but could it be handled differently?

**Comment by kr-g** [comment]
Oh. Wow. Thonny.
I m using it from thonny too.!
Will have a look if i can reproduce if here on my system

Jens Diemer <notifications@github.com> schrieb am Sa., 7. Dez. 2019, 10:09:

**Comment by jedie** [comment]
I didn't run it from thonny. I run it seperate, but thonny is also running and connected.

**Comment by kr-g** [comment]
If 2 processes are attached to one serial device it will fail.
This will also happen if you use eg. mpfshell in addition to your upgrade
tool

Jens Diemer <notifications@github.com> schrieb am Sa., 7. Dez. 2019, 11:29:

**Comment by kr-g** [comment]
Not a bug. Works as expected.
